- name: Five machines fio write test 
  hosts: testmachine5
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - name: fio random write test 
      shell: fio --time_based --name=benchmark --size=10G --runtime=300 --filename=fio-random-write --ioengine=libaio --randrepeat=0 --iodepth=128 --direct=1 --invalidate=1 --verify=0 --verify_fatal=0 --numjobs=4 --rw=randwrite --blocksize=16k --group_reporting
      async: 360
      poll: 10
      register: fio_random_write_output

    - name: make sure files are deleted
      shell: rm -f fio-random-write


    - copy:
        content: "{% for host in groups.testmachine5 %}------- fio random write {{host}}  -------\n{{ hostvars[host].fio_random_write_output.stdout }}\n=============={% endfor %}"
        dest: ./5fiowrite.out
      delegate_to: localhost
      run_once: true
