- name: All machines MYSQL OLTP test 
  hosts: testmachines
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - name: sysbench cpu test
      shell: sysbench --test=cpu --cpu-max-prime=20000 --num-threads=2 run
      async: 600
      poll: 10
      register: sysbench_cpu_test_output

    - name: sysbench memory read
      shell: sysbench --test=memory --memory-block-size=1K --memory-scope=global --memory-total-size=100G --memory-oper=read run
      async: 600
      poll: 10
      register: sysbench_memory_read_output

    - name: sysbench memory write
      shell: sysbench --test=memory --memory-block-size=1K --memory-scope=global --memory-total-size=100G --memory-oper=write run
      async: 600
      poll: 10
      register: sysbench_memory_write_output

    - copy:
        content: "{% for host in groups.testmachines %}------- sysbench cpu {{host}}  -------\n{{ hostvars[host].sysbench_cpu_test_output.stdout }}\n==============\n------- sysbench memory read {{host}}  -------\n{{ hostvars[host].sysbench_memory_read_output.stdout }}\n==============\n------- sysbench memory write {{host}}  -------\n{{ hostvars[host].sysbench_memory_write_output.stdout }}\n==============\n{% endfor %}"
        dest: ./allcpuandmemory.out
      delegate_to: localhost
      run_once: true
